import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialProductionSchema1779897600000 implements MigrationInterface {
  name = 'InitialProductionSchema1779897600000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const queries = [
      'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"',
      'CREATE TYPE "project_members_role_enum" AS ENUM(\'owner\', \'admin\', \'member\', \'viewer\')',
      'CREATE TYPE "agents_runtime_enum" AS ENUM(\'python\', \'nodejs\', \'docker\')',
      'CREATE TYPE "agents_status_enum" AS ENUM(\'active\', \'inactive\', \'idle\', \'error\')',
      'CREATE TYPE "messages_role_enum" AS ENUM(\'user\', \'agent\', \'system\')',
      'CREATE TYPE "messages_visibility_enum" AS ENUM(\'session\', \'direct\')',
      'CREATE TYPE "sessions_status_enum" AS ENUM(\'active\', \'closed\', \'archived\')',
      'CREATE TYPE "event_idempotency_keys_status_enum" AS ENUM(\'reserved\', \'committed\')',
      'CREATE TYPE "agent_runs_status_enum" AS ENUM(\'queued\', \'running\', \'completed\', \'failed\')',
      'CREATE TYPE "project_incidents_severity_enum" AS ENUM(\'critical\', \'warning\', \'info\')',
      'CREATE TYPE "project_incidents_status_enum" AS ENUM(\'active\', \'resolved\', \'acknowledged\')',
      'CREATE TABLE "project_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" "project_members_role_enum" NOT NULL DEFAULT \'member\', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b3f491d3a3f986106d281d8eb4b" UNIQUE ("project_id", "user_id"), CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))',
      'CREATE TABLE "agents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "name" character varying(128) NOT NULL, "description" text, "runtime" "agents_runtime_enum" NOT NULL DEFAULT \'python\', "config_json" text, "api_key_hash" character varying(255), "status" "agents_status_enum" NOT NULL DEFAULT \'active\', "last_heartbeat_at" TIMESTAMP, "metrics_json" text DEFAULT \'{}\', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c653f28ae19c5884d5baf6a1d9" PRIMARY KEY ("id"))',
      'CREATE TABLE "session_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" uuid NOT NULL, "agent_id" uuid NOT NULL, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1ec2510dd4dab656b533b0237e8" UNIQUE ("session_id", "agent_id"), CONSTRAINT "PK_f186de01f7f809e45eaa9bd5b84" PRIMARY KEY ("id"))',
      'CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid, "session_id" uuid NOT NULL, "event_id" uuid, "seq" integer, "agent_id" uuid, "user_id" uuid, "sender_type" character varying(32), "source_message_id" character varying(128), "role" "messages_role_enum" NOT NULL, "content" text NOT NULL, "content_type" character varying(64) NOT NULL DEFAULT \'text\', "parent_message_id" character varying(128), "visibility" "messages_visibility_enum" NOT NULL DEFAULT \'session\', "recipient_participant_ids" text, "details" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))',
      'CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" uuid NOT NULL, "seq" integer NOT NULL, "project_id" uuid NOT NULL, "agent_id" uuid, "user_id" uuid, "actor_type" character varying(32), "type" character varying(64) NOT NULL, "idempotency_key" character varying(160), "aggregate_type" character varying(64), "aggregate_id" character varying(128), "payload_json" text NOT NULL DEFAULT \'{}\', "metadata_json" text, "schema_version" integer NOT NULL DEFAULT \'1\', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "trace_id" character varying(64), "correlation_id" character varying(128), CONSTRAINT "UQ_6ae84218c1be1523b4566426399" UNIQUE ("session_id", "seq"), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))',
      'CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "title" character varying(255), "status" "sessions_status_enum" NOT NULL DEFAULT \'active\', "last_seq" integer NOT NULL DEFAULT \'0\', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "version" integer NOT NULL, CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))',
      'CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "webhookUrl" character varying, "webhookSecret" character varying, "webhookEnabledEvents" text DEFAULT \'[]\', "owner_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))',
      'CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "display_name" character varying(128) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))',
      'CREATE TABLE "event_idempotency_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "session_id" uuid NOT NULL, "idempotency_key" character varying(160) NOT NULL, "request_hash" character varying(64) NOT NULL, "status" "event_idempotency_keys_status_enum" NOT NULL DEFAULT \'reserved\', "event_id" uuid, "committed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a8409b16ec43ce7fb6eb9f92c65" UNIQUE ("session_id", "idempotency_key"), CONSTRAINT "PK_769c9dd3f8de2ac79e5ac86d239" PRIMARY KEY ("id"))',
      'CREATE TABLE "agent_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "session_id" uuid NOT NULL, "agent_id" uuid NOT NULL, "run_id" character varying(128) NOT NULL, "status" "agent_runs_status_enum" NOT NULL DEFAULT \'queued\', "attempt" integer NOT NULL DEFAULT \'1\', "delivery_id" character varying(128), "trigger_event_id" uuid, "queued_event_id" uuid, "started_event_id" uuid, "terminal_event_id" uuid, "queued_at" TIMESTAMP, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "failed_at" TIMESTAMP, "duration_ms" integer, "error_json" text, "metrics_json" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_763f2791166dcaf6f7334671cee" UNIQUE ("session_id", "run_id"), CONSTRAINT "PK_442f7e0ec4ae860cf17edc57825" PRIMARY KEY ("id"))',
      'CREATE TABLE "health_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "session_id" uuid, "agent_id" uuid, "run_id" character varying(128), "event_id" uuid NOT NULL, "name" character varying(128) NOT NULL, "value" real NOT NULL, "unit" character varying(64), "status" character varying(64), "tags_json" text, "details_json" text, "recorded_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_46d4d3eb324a0bf5c90b5b38305" UNIQUE ("event_id"), CONSTRAINT "PK_2c89a8302441086a0fe3797e477" PRIMARY KEY ("id"))',
      'CREATE TABLE "incidents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agent_id" character varying(64) NOT NULL, "type" character varying(32) NOT NULL, "severity" character varying(16) NOT NULL, "status" character varying(20) NOT NULL DEFAULT \'open\', "message" text NOT NULL, "details" text NOT NULL DEFAULT \'{}\', "resolved_at" TIMESTAMP, "resolved_by" character varying(64), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ccb34c01719889017e2246469f9" PRIMARY KEY ("id"))',
      'CREATE TABLE "project_incidents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "severity" "project_incidents_severity_enum" NOT NULL, "status" "project_incidents_status_enum" NOT NULL DEFAULT \'active\', "title" character varying(255) NOT NULL, "description_json" text, "resolved_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_246110016a0a29f8799c75daf00" PRIMARY KEY ("id"))',
      'CREATE TABLE "mcp_capabilities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" character varying NOT NULL, "agent_id" character varying NOT NULL, "name" character varying(255) NOT NULL, "description" text, "schema_json" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_22b156d96ec20d71ecef68fce7e" PRIMARY KEY ("id"))',
      'CREATE UNIQUE INDEX "IDX_46b8af64422890b3ca2511cb31" ON "messages" ("event_id") ',
      'CREATE INDEX "IDX_6be0ecc5abdb5e72a6c959a2b6" ON "messages" ("session_id", "created_at") ',
      'CREATE INDEX "IDX_d44626799648caec5aa5586eb6" ON "events" ("project_id", "type", "created_at") ',
      'CREATE INDEX "IDX_8ec5f2b395ee274573a6f35284" ON "events" ("session_id", "idempotency_key") ',
      'CREATE INDEX "IDX_6ae84218c1be1523b456642639" ON "events" ("session_id", "seq") ',
      'CREATE INDEX "IDX_8293a3267289d30aadf3d37726" ON "event_idempotency_keys" ("project_id", "idempotency_key") ',
      'CREATE INDEX "IDX_0c600fd8c6ccb1dde5e5e606a2" ON "agent_runs" ("session_id", "status") ',
      'CREATE INDEX "IDX_e269d23c49911e73b2ee1fecaf" ON "agent_runs" ("project_id", "agent_id", "status") ',
      'CREATE INDEX "IDX_565af082320273597b70748f7d" ON "health_metrics" ("session_id", "recorded_at") ',
      'CREATE INDEX "IDX_8961aa0a28f34e1bb95f095f21" ON "health_metrics" ("project_id", "agent_id", "recorded_at") ',
      'CREATE INDEX "IDX_d1beb9b52ec9177d6f5dc043a9" ON "incidents" ("type", "status") ',
      'CREATE INDEX "IDX_54f43eead15e12a66dbcf3b267" ON "incidents" ("agent_id", "status", "created_at") ',
      'CREATE INDEX "IDX_18121ed347909b052c935e742b" ON "project_incidents" ("project_id", "status", "created_at") ',
      'ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "agents" ADD CONSTRAINT "FK_90f24a22f7af11b155cd4752e65" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "session_participants" ADD CONSTRAINT "FK_0f44aaaaf807cef66c6fa9494a8" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "session_participants" ADD CONSTRAINT "FK_1f56af0a0f1d8c583a4fde6241c" FOREIGN KEY ("agent_id") REFERENCES "agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "messages" ADD CONSTRAINT "FK_ff71b7760071ed9caba7f02beb4" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "events" ADD CONSTRAINT "FK_f3069564d09456ff375a0d0c54b" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "sessions" ADD CONSTRAINT "FK_d9ea2f57c99bf176e702f2d3aef" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "projects" ADD CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "event_idempotency_keys" ADD CONSTRAINT "FK_64ce9f19d9f94b9bfe93f291908" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "event_idempotency_keys" ADD CONSTRAINT "FK_0144d39665771759c012628f09d" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "agent_runs" ADD CONSTRAINT "FK_f60e6d1c99876309156f6ac7482" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "agent_runs" ADD CONSTRAINT "FK_15de117c8da5feee8a1e6561447" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "agent_runs" ADD CONSTRAINT "FK_b7e54bda53308d1c35f163440b7" FOREIGN KEY ("agent_id") REFERENCES "agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "agent_runs" ADD CONSTRAINT "FK_23ce10ca975baacb1a65d3517bc" FOREIGN KEY ("queued_event_id") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "health_metrics" ADD CONSTRAINT "FK_a9c59581c781d6d7d150f207b9a" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "health_metrics" ADD CONSTRAINT "FK_1f18750c4174d6715cafe0842c3" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "health_metrics" ADD CONSTRAINT "FK_04bd4e02ce9de78946cce4a8b21" FOREIGN KEY ("agent_id") REFERENCES "agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
      'ALTER TABLE "health_metrics" ADD CONSTRAINT "FK_46d4d3eb324a0bf5c90b5b38305" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION',
    ];

    for (const query of queries) {
      await queryRunner.query(query);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const queries = [
      'ALTER TABLE "health_metrics" DROP CONSTRAINT "FK_46d4d3eb324a0bf5c90b5b38305"',
      'ALTER TABLE "health_metrics" DROP CONSTRAINT "FK_04bd4e02ce9de78946cce4a8b21"',
      'ALTER TABLE "health_metrics" DROP CONSTRAINT "FK_1f18750c4174d6715cafe0842c3"',
      'ALTER TABLE "health_metrics" DROP CONSTRAINT "FK_a9c59581c781d6d7d150f207b9a"',
      'ALTER TABLE "agent_runs" DROP CONSTRAINT "FK_23ce10ca975baacb1a65d3517bc"',
      'ALTER TABLE "agent_runs" DROP CONSTRAINT "FK_b7e54bda53308d1c35f163440b7"',
      'ALTER TABLE "agent_runs" DROP CONSTRAINT "FK_15de117c8da5feee8a1e6561447"',
      'ALTER TABLE "agent_runs" DROP CONSTRAINT "FK_f60e6d1c99876309156f6ac7482"',
      'ALTER TABLE "event_idempotency_keys" DROP CONSTRAINT "FK_0144d39665771759c012628f09d"',
      'ALTER TABLE "event_idempotency_keys" DROP CONSTRAINT "FK_64ce9f19d9f94b9bfe93f291908"',
      'ALTER TABLE "projects" DROP CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf"',
      'ALTER TABLE "sessions" DROP CONSTRAINT "FK_d9ea2f57c99bf176e702f2d3aef"',
      'ALTER TABLE "events" DROP CONSTRAINT "FK_f3069564d09456ff375a0d0c54b"',
      'ALTER TABLE "messages" DROP CONSTRAINT "FK_ff71b7760071ed9caba7f02beb4"',
      'ALTER TABLE "session_participants" DROP CONSTRAINT "FK_1f56af0a0f1d8c583a4fde6241c"',
      'ALTER TABLE "session_participants" DROP CONSTRAINT "FK_0f44aaaaf807cef66c6fa9494a8"',
      'ALTER TABLE "agents" DROP CONSTRAINT "FK_90f24a22f7af11b155cd4752e65"',
      'ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"',
      'ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"',
      'DROP INDEX "IDX_18121ed347909b052c935e742b"',
      'DROP INDEX "IDX_54f43eead15e12a66dbcf3b267"',
      'DROP INDEX "IDX_d1beb9b52ec9177d6f5dc043a9"',
      'DROP INDEX "IDX_8961aa0a28f34e1bb95f095f21"',
      'DROP INDEX "IDX_565af082320273597b70748f7d"',
      'DROP INDEX "IDX_e269d23c49911e73b2ee1fecaf"',
      'DROP INDEX "IDX_0c600fd8c6ccb1dde5e5e606a2"',
      'DROP INDEX "IDX_8293a3267289d30aadf3d37726"',
      'DROP INDEX "IDX_6ae84218c1be1523b456642639"',
      'DROP INDEX "IDX_8ec5f2b395ee274573a6f35284"',
      'DROP INDEX "IDX_d44626799648caec5aa5586eb6"',
      'DROP INDEX "IDX_6be0ecc5abdb5e72a6c959a2b6"',
      'DROP INDEX "IDX_46b8af64422890b3ca2511cb31"',
      'DROP TABLE "mcp_capabilities"',
      'DROP TABLE "project_incidents"',
      'DROP TABLE "incidents"',
      'DROP TABLE "health_metrics"',
      'DROP TABLE "agent_runs"',
      'DROP TABLE "event_idempotency_keys"',
      'DROP TABLE "users"',
      'DROP TABLE "projects"',
      'DROP TABLE "sessions"',
      'DROP TABLE "events"',
      'DROP TABLE "messages"',
      'DROP TABLE "session_participants"',
      'DROP TABLE "agents"',
      'DROP TABLE "project_members"',
      'DROP TYPE "project_incidents_status_enum"',
      'DROP TYPE "project_incidents_severity_enum"',
      'DROP TYPE "agent_runs_status_enum"',
      'DROP TYPE "event_idempotency_keys_status_enum"',
      'DROP TYPE "sessions_status_enum"',
      'DROP TYPE "messages_visibility_enum"',
      'DROP TYPE "messages_role_enum"',
      'DROP TYPE "agents_status_enum"',
      'DROP TYPE "agents_runtime_enum"',
      'DROP TYPE "project_members_role_enum"',
    ];

    for (const query of queries) {
      await queryRunner.query(query);
    }
  }
}
